-- =====================================================================
-- SQL 57 — Bônus de indicação (R$ 10 no saldo do Banco por amigo)
-- Idempotente (pode rodar mais de uma vez). Transacional (BEGIN/COMMIT). Sem barras invertidas.
--
-- Regras (tudo no servidor, nada credita a partir do cliente):
--  * Quem compartilha o link ganha R$ 10 de saldo REAL (caixa_saldos) por amigo
--    que se cadastrou pelo link E fez o PRIMEIRO depósito confirmado (mín. R$ 50).
--  * 1 bônus por conta indicada (UNIQUE indicado_auth). Idempotente: só credita
--    linha em status 'cadastrou' travada com FOR UPDATE.
--  * Auto-indicação bloqueada: mesmo auth, mesmo e-mail, mesmo telefone/CPF
--    (quando existirem em auth.users / metadata / emprestimos.telefone).
--    Conta indicada precisa ser nova (criada há <= 7 dias) e sem depósito anterior.
--  * Programa pausável: app_flags.indicacao_bonus_ativo (false = não inscreve nem credita).
--  * Depósito mínimo R$ 50 (app_flags.caixa_deposito_minimo) — validado no INSERT.
--  * Saque de conta que JÁ RECEBEU bônus: saldo >= R$ 100 e primeiro depósito
--    confirmado (nessa ordem). Contas sem bônus: regras antigas inalteradas.
--  * Banner pode ser pago com saldo do Banco (RPC banner_pagar_com_saldo):
--    debita o preço e marca o banner como pago (admin libera como de costume).
-- Depende de: 15 (caixa), 16/51 (indicação), 35 (app_flags), 50 (banners).
-- =====================================================================
BEGIN;


-- 0) Flags ------------------------------------------------------------
INSERT INTO public.app_flags (key, value_bool, value_text)
VALUES ('indicacao_bonus_ativo', true, 'R$ 10 por amigo (1º depósito do amigo)')
ON CONFLICT (key) DO NOTHING;
INSERT INTO public.app_flags (key, value_bool, value_text)
VALUES ('caixa_deposito_minimo', NULL, '50')
ON CONFLICT (key) DO NOTHING;

-- 1) Tabela -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.indicacao_bonus (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicador_auth  uuid NOT NULL,
  indicado_auth   uuid NOT NULL,
  indicado_nome   text,
  codigo          text,
  status          text NOT NULL DEFAULT 'cadastrou',
  motivo          text,
  valor           numeric(10,2) NOT NULL DEFAULT 10,
  deposito_id     integer,
  movimento_id    integer,
  criado_em       timestamptz NOT NULL DEFAULT now(),
  liberado_em     timestamptz,
  CONSTRAINT indicacao_bonus_indicado_uq UNIQUE (indicado_auth),
  CONSTRAINT indicacao_bonus_status_chk CHECK (status IN ('cadastrou', 'liberado', 'bloqueado'))
);
CREATE INDEX IF NOT EXISTS indicacao_bonus_indicador_idx ON public.indicacao_bonus (indicador_auth, criado_em DESC);

ALTER TABLE public.indicacao_bonus ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.indicacao_bonus FROM anon, authenticated;
GRANT SELECT ON public.indicacao_bonus TO authenticated;
DROP POLICY IF EXISTS indicacao_bonus_select_own_or_admin ON public.indicacao_bonus;
CREATE POLICY indicacao_bonus_select_own_or_admin ON public.indicacao_bonus
  FOR SELECT TO authenticated
  USING (indicador_auth = auth.uid() OR public.is_admin());

-- 2) Helpers (internos: sem EXECUTE para clientes) ----------------------
CREATE OR REPLACE FUNCTION public.ib_programa_ativo()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT value_bool FROM public.app_flags WHERE key = 'indicacao_bonus_ativo'), true);
$$;

CREATE OR REPLACE FUNCTION public.caixa_deposito_minimo()
RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    (SELECT CASE WHEN replace(value_text, ',', '.') ~ '^[0-9]+([.][0-9]{1,2})?$'
                 THEN replace(value_text, ',', '.')::numeric END
       FROM public.app_flags WHERE key = 'caixa_deposito_minimo'),
    50);
$$;

CREATE OR REPLACE FUNCTION public.ib_tem_primeiro_deposito(p_uid uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.caixa_deposito_pedidos d
                  WHERE d.auth_id = p_uid AND d.status = 'confirmado' AND d.valor > 0);
$$;

-- identificadores normalizados (tel:<últimos 11 dígitos>, cpf:<11 dígitos>, email:<lower>)
CREATE OR REPLACE FUNCTION public.ib_identificadores(p_uid uuid)
RETURNS text[] LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record; out text[] := '{}'; d text;
BEGIN
  SELECT au.email, au.phone, au.raw_user_meta_data AS m INTO r FROM auth.users au WHERE au.id = p_uid;
  IF FOUND THEN
    IF r.email IS NOT NULL THEN out := out || ('email:' || lower(trim(r.email))); END IF;
    FOREACH d IN ARRAY ARRAY[r.phone, r.m ->> 'telefone', r.m ->> 'whatsapp', r.m ->> 'phone'] LOOP
      d := regexp_replace(COALESCE(d, ''), '[^0-9]', '', 'g');
      IF length(d) >= 10 THEN out := out || ('tel:' || right(d, 11)); END IF;
    END LOOP;
    d := regexp_replace(COALESCE(r.m ->> 'cpf', ''), '[^0-9]', '', 'g');
    IF length(d) = 11 THEN out := out || ('cpf:' || d); END IF;
  END IF;
  SELECT lower(trim(u.email)) INTO d FROM public.usuarios u WHERE u.auth_id = p_uid LIMIT 1;
  IF d IS NOT NULL THEN out := out || ('email:' || d); END IF;
  FOR d IN SELECT regexp_replace(COALESCE(e.telefone, ''), '[^0-9]', '', 'g') FROM public.emprestimos e WHERE e.auth_id = p_uid LOOP
    IF length(d) >= 10 THEN out := out || ('tel:' || right(d, 11)); END IF;
  END LOOP;
  RETURN out;
END;
$$;

CREATE OR REPLACE FUNCTION public.ib_mesma_pessoa(a uuid, b uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT a = b OR (public.ib_identificadores(a) && public.ib_identificadores(b));
$$;

REVOKE ALL ON FUNCTION public.ib_tem_primeiro_deposito(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ib_identificadores(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ib_mesma_pessoa(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ib_programa_ativo() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ib_programa_ativo() TO authenticated;
GRANT EXECUTE ON FUNCTION public.caixa_deposito_minimo() TO anon, authenticated;

-- 3) Inscrição: quando usuarios.indicado_por é gravado (só via processar_indicacao)
CREATE OR REPLACE FUNCTION public.tg_indicacao_bonus_inscrever()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_ref uuid; v_criado timestamptz; v_status text := 'cadastrou'; v_motivo text;
BEGIN
  IF NEW.indicado_por IS NULL OR NEW.indicado_por = '' OR NEW.auth_id IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND COALESCE(OLD.indicado_por, '') <> '' THEN RETURN NEW; END IF;
  IF NOT public.ib_programa_ativo() THEN RETURN NEW; END IF;
  BEGIN
    SELECT u.auth_id INTO v_ref FROM public.usuarios u
     WHERE upper(u.codigo_indicacao) = upper(trim(NEW.indicado_por)) LIMIT 1;
    IF v_ref IS NULL THEN RETURN NEW; END IF;
    SELECT au.created_at INTO v_criado FROM auth.users au WHERE au.id = NEW.auth_id;
    IF public.ib_mesma_pessoa(v_ref, NEW.auth_id) THEN
      v_status := 'bloqueado'; v_motivo := 'auto-indicação (mesma conta/e-mail/telefone/CPF)';
    ELSIF v_criado IS NOT NULL AND v_criado < now() - interval '7 days' THEN
      v_status := 'bloqueado'; v_motivo := 'conta antiga (não é cadastro novo pelo link)';
    ELSIF public.ib_tem_primeiro_deposito(NEW.auth_id) THEN
      v_status := 'bloqueado'; v_motivo := 'já tinha depósito antes da indicação';
    END IF;
    INSERT INTO public.indicacao_bonus (indicador_auth, indicado_auth, indicado_nome, codigo, status, motivo)
    VALUES (v_ref, NEW.auth_id, left(COALESCE(NULLIF(trim(NEW.apelido), ''), split_part(trim(NEW.nome), ' ', 1)), 40),
            upper(trim(NEW.indicado_por)), v_status, v_motivo)
    ON CONFLICT (indicado_auth) DO NOTHING;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'indicacao_bonus inscrever: %', SQLERRM;  -- nunca quebra o cadastro
  END;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_indicacao_bonus_inscrever ON public.usuarios;
CREATE TRIGGER trg_indicacao_bonus_inscrever
  AFTER INSERT OR UPDATE OF indicado_por ON public.usuarios
  FOR EACH ROW EXECUTE FUNCTION public.tg_indicacao_bonus_inscrever();

-- 4) Crédito: 1º depósito confirmado (>= mínimo) do indicado ----------------
CREATE OR REPLACE FUNCTION public.tg_indicacao_bonus_creditar()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  ib public.indicacao_bonus; v_saldo numeric; v_mov integer;
BEGIN
  IF NEW.status IS DISTINCT FROM 'confirmado' THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND OLD.status IS NOT DISTINCT FROM 'confirmado' THEN RETURN NEW; END IF;
  IF COALESCE(NEW.valor, 0) < public.caixa_deposito_minimo() THEN RETURN NEW; END IF;
  IF NOT public.ib_programa_ativo() THEN RETURN NEW; END IF;

  SELECT * INTO ib FROM public.indicacao_bonus
   WHERE indicado_auth = NEW.auth_id AND status = 'cadastrou' FOR UPDATE;
  IF NOT FOUND THEN RETURN NEW; END IF;
  IF public.ib_mesma_pessoa(ib.indicador_auth, ib.indicado_auth) THEN
    UPDATE public.indicacao_bonus SET status = 'bloqueado', motivo = 'auto-indicação (detectada no depósito)' WHERE id = ib.id;
    RETURN NEW;
  END IF;

  INSERT INTO public.caixa_saldos (auth_id, saldo, taxa_mensal, taxa_yield_max)
  VALUES (ib.indicador_auth, 0, 5, 5) ON CONFLICT (auth_id) DO NOTHING;
  UPDATE public.caixa_saldos
     SET saldo = round(COALESCE(saldo, 0) + ib.valor, 2), atualizado_em = now()
   WHERE auth_id = ib.indicador_auth
   RETURNING saldo INTO v_saldo;
  INSERT INTO public.caixa_movimentos (auth_id, tipo, valor, saldo_apos, observacao)
  VALUES (ib.indicador_auth, 'bonus_indicacao', ib.valor, v_saldo,
          'Bônus de indicação' || COALESCE(' — ' || ib.indicado_nome, ''))
  RETURNING id INTO v_mov;
  UPDATE public.indicacao_bonus
     SET status = 'liberado', liberado_em = now(), deposito_id = NEW.id, movimento_id = v_mov, motivo = NULL
   WHERE id = ib.id;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_indicacao_bonus_creditar ON public.caixa_deposito_pedidos;
CREATE TRIGGER trg_indicacao_bonus_creditar
  AFTER INSERT OR UPDATE OF status ON public.caixa_deposito_pedidos
  FOR EACH ROW EXECUTE FUNCTION public.tg_indicacao_bonus_creditar();

-- 5) Depósito mínimo (cliente) -------------------------------------------
CREATE OR REPLACE FUNCTION public.tg_caixa_deposito_minimo()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_min numeric := public.caixa_deposito_minimo();
BEGIN
  IF auth.uid() IS NULL OR public.is_admin() THEN RETURN NEW; END IF;
  IF COALESCE(NEW.valor, 0) < v_min THEN
    RAISE EXCEPTION 'Depósito mínimo: R$ %', replace(to_char(v_min, 'FM999990.00'), '.', ',') USING ERRCODE = '22023';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_caixa_dep_minimo ON public.caixa_deposito_pedidos;
CREATE TRIGGER trg_caixa_dep_minimo
  BEFORE INSERT ON public.caixa_deposito_pedidos
  FOR EACH ROW EXECUTE FUNCTION public.tg_caixa_deposito_minimo();

-- 6) Saque de quem recebeu bônus: saldo >= 100, depois 1º depósito ---------
CREATE OR REPLACE FUNCTION public.caixa_saque_status()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid uuid := auth.uid(); v_saldo numeric; v_bonus numeric;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'login necessário' USING ERRCODE = '42501'; END IF;
  SELECT COALESCE(saldo, 0) INTO v_saldo FROM public.caixa_saldos WHERE auth_id = v_uid;
  SELECT COALESCE(sum(valor), 0) INTO v_bonus FROM public.indicacao_bonus WHERE indicador_auth = v_uid AND status = 'liberado';
  RETURN jsonb_build_object(
    'saldo', COALESCE(v_saldo, 0),
    'bonus_total', v_bonus,
    'tem_bonus', v_bonus > 0,
    'primeiro_deposito', public.ib_tem_primeiro_deposito(v_uid),
    'saque_minimo_bonus', 100,
    'deposito_minimo', public.caixa_deposito_minimo());
END;
$$;
REVOKE ALL ON FUNCTION public.caixa_saque_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.caixa_saque_status() TO authenticated;

CREATE OR REPLACE FUNCTION public.tg_caixa_saque_bonus_guard()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_saldo numeric;
BEGIN
  -- vale também para admin sacando da PRÓPRIA conta
  IF auth.uid() IS NULL OR NEW.auth_id IS DISTINCT FROM auth.uid() THEN RETURN NEW; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.indicacao_bonus WHERE indicador_auth = NEW.auth_id AND status = 'liberado') THEN
    RETURN NEW;
  END IF;
  SELECT COALESCE(saldo, 0) INTO v_saldo FROM public.caixa_saldos WHERE auth_id = NEW.auth_id;
  IF COALESCE(v_saldo, 0) < 100 THEN
    RAISE EXCEPTION 'Os ganhos de indicação podem ser sacados a partir de R$ 100' USING ERRCODE = '42501';
  END IF;
  IF NOT public.ib_tem_primeiro_deposito(NEW.auth_id) THEN
    RAISE EXCEPTION 'Para liberar o saque, faça seu primeiro depósito (depósito mínimo R$ 50)' USING ERRCODE = '42501';
  END IF;
  IF COALESCE(NEW.valor, 0) > v_saldo THEN
    RAISE EXCEPTION 'Saldo insuficiente' USING ERRCODE = '22023';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_caixa_saque_bonus_guard ON public.caixa_saque_pedidos;
CREATE TRIGGER trg_caixa_saque_bonus_guard
  BEFORE INSERT ON public.caixa_saque_pedidos
  FOR EACH ROW EXECUTE FUNCTION public.tg_caixa_saque_bonus_guard();

-- 7) Resumo para a área de compartilhar -----------------------------------
CREATE OR REPLACE FUNCTION public.indicacao_bonus_resumo()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'login necessário' USING ERRCODE = '42501'; END IF;
  RETURN jsonb_build_object(
    'ativo', public.ib_programa_ativo(),
    'valor', 10,
    'total', (SELECT COALESCE(sum(valor), 0) FROM public.indicacao_bonus WHERE indicador_auth = v_uid AND status = 'liberado'),
    'amigos', COALESCE((SELECT jsonb_agg(jsonb_build_object(
                  'nome', COALESCE(b.indicado_nome, 'Amigo'),
                  'status', b.status,
                  'criado_em', b.criado_em,
                  'liberado_em', b.liberado_em) ORDER BY b.criado_em DESC)
               FROM (SELECT * FROM public.indicacao_bonus WHERE indicador_auth = v_uid AND status <> 'bloqueado'
                      ORDER BY criado_em DESC LIMIT 100) b), '[]'::jsonb));
END;
$$;
REVOKE ALL ON FUNCTION public.indicacao_bonus_resumo() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.indicacao_bonus_resumo() TO authenticated;

-- 8) Admin: lista de bônus ------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_indicacao_bonus_lista(p_limit integer DEFAULT 200)
RETURNS TABLE(id bigint, status text, motivo text, valor numeric, criado_em timestamptz, liberado_em timestamptz,
              indicador_email text, indicador_nome text, indicado_email text, indicado_nome text, deposito_id integer)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT COALESCE(public.is_admin(), false) THEN
    RAISE EXCEPTION 'só admin' USING ERRCODE = '42501';
  END IF;
  RETURN QUERY
  SELECT b.id, b.status, b.motivo, b.valor::numeric, b.criado_em, b.liberado_em,
         ui.email::text, COALESCE(ui.apelido, ui.nome)::text, ud.email::text, COALESCE(ud.apelido, ud.nome, b.indicado_nome)::text, b.deposito_id
    FROM public.indicacao_bonus b
    LEFT JOIN public.usuarios ui ON ui.auth_id = b.indicador_auth
    LEFT JOIN public.usuarios ud ON ud.auth_id = b.indicado_auth
   ORDER BY b.criado_em DESC
   LIMIT GREATEST(1, LEAST(COALESCE(p_limit, 200), 1000));
END;
$$;
REVOKE ALL ON FUNCTION public.admin_indicacao_bonus_lista(integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_indicacao_bonus_lista(integer) TO authenticated;

-- 9) Banner pago com saldo do Banco ----------------------------------------
CREATE OR REPLACE FUNCTION public.banner_pagar_com_saldo(p_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid uuid := auth.uid(); b public.banners_pagos; v_preco numeric := public.banner_preco();
  v_saldo numeric; v_mov integer;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'login necessário' USING ERRCODE = '42501'; END IF;
  IF NOT COALESCE((SELECT value_bool FROM public.app_flags WHERE key = 'minera_bank_enabled'), true) THEN
    RAISE EXCEPTION 'Banco em manutenção' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO b FROM public.banners_pagos WHERE id = p_id AND auth_id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'banner: não encontrado' USING ERRCODE = 'P0002'; END IF;
  IF b.status IN ('bloqueado', 'recusado') THEN RAISE EXCEPTION 'banner: %', b.status USING ERRCODE = '42501'; END IF;
  IF b.comprovante_em IS NOT NULL THEN RAISE EXCEPTION 'banner: pagamento já enviado' USING ERRCODE = '42501'; END IF;
  IF NOT (b.status = 'aguardando_pagamento' OR (b.status = 'ativo' AND b.renovacao_pedida_em IS NOT NULL)) THEN
    RAISE EXCEPTION 'banner: nada a pagar agora' USING ERRCODE = '42501';
  END IF;
  IF EXISTS (SELECT 1 FROM public.indicacao_bonus WHERE indicador_auth = v_uid AND status = 'liberado')
     AND NOT public.ib_tem_primeiro_deposito(v_uid) THEN
    RAISE EXCEPTION 'Para usar o saldo, faça seu primeiro depósito (depósito mínimo R$ 50)' USING ERRCODE = '42501';
  END IF;
  SELECT saldo INTO v_saldo FROM public.caixa_saldos WHERE auth_id = v_uid FOR UPDATE;
  IF COALESCE(v_saldo, 0) < v_preco THEN RAISE EXCEPTION 'Saldo insuficiente no Banco' USING ERRCODE = '22023'; END IF;
  UPDATE public.caixa_saldos SET saldo = round(saldo - v_preco, 2), atualizado_em = now()
   WHERE auth_id = v_uid RETURNING saldo INTO v_saldo;
  INSERT INTO public.caixa_movimentos (auth_id, tipo, valor, saldo_apos, observacao)
  VALUES (v_uid, 'banner', v_preco, v_saldo, 'Banner #' || p_id || ' pago com saldo')
  RETURNING id INTO v_mov;
  UPDATE public.banners_pagos
     SET comprovante_em = now(),
         status = CASE WHEN status = 'aguardando_pagamento' THEN 'comprovante_enviado' ELSE status END,
         motivo = 'Pago com saldo do Banco (mov #' || v_mov || ')'
   WHERE id = p_id;
  RETURN jsonb_build_object('ok', true, 'saldo', v_saldo, 'valor', v_preco, 'movimento_id', v_mov);
END;
$$;
REVOKE ALL ON FUNCTION public.banner_pagar_com_saldo(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.banner_pagar_com_saldo(bigint) TO authenticated;

-- Trigger functions: sem EXECUTE direto para clientes
REVOKE ALL ON FUNCTION public.tg_indicacao_bonus_inscrever() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.tg_indicacao_bonus_creditar() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.tg_caixa_deposito_minimo() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.tg_caixa_saque_bonus_guard() FROM PUBLIC, anon, authenticated;

-- Conferência
SELECT
  (SELECT count(*) FROM pg_trigger WHERE tgname IN ('trg_indicacao_bonus_inscrever','trg_indicacao_bonus_creditar','trg_caixa_dep_minimo','trg_caixa_saque_bonus_guard')) AS triggers_4,
  (SELECT relrowsecurity FROM pg_class WHERE oid = 'public.indicacao_bonus'::regclass) AS rls_on,
  has_table_privilege('authenticated', 'public.indicacao_bonus', 'INSERT') AS auth_insert_false,
  (SELECT value_bool FROM public.app_flags WHERE key = 'indicacao_bonus_ativo') AS programa_ativo,
  public.caixa_deposito_minimo() AS deposito_minimo;

COMMIT;
